#!/bin/bash

#########################################################################
#
# E-mail inactivity report / alert to be used with DirecAdmin control 
# panel with Dovecot Maildir.
#
# More useful if used as cronjob, especially at server low load periods.
# Example to run every 15 days at 6:35 a.m.:
#
# Create a cronjob file (/etc/cron.d/alert-pop-inactivity.cron) with the line:
# 35 6 */15 * * root /path/alert-pop-inactivity.sh --email
# Remember to change the /path, chmod this script to 700 and chown to root
#
# Author: Victor Benincasa (vbenincasa @ gmail.com) 
# Originally developed for Unihost Brasil (http://unihostbrasil.com.br)
#
# Free to use and redistribute, just keep the original credits.
#
# V 2.8 08/06/2021
#
#########################################################################

############################################# 
# CONFIGURATION
#

# Inactivity alert threshold (days). Suggested value: 90 (quarter year)
ALERT_THRESHOLD=90

# From address used to send e-mail to users and admin
ALERT_EMAIL_FROM_NAME="Webhosting Company Name"
ALERT_EMAIL_FROM="sendermail@domain.com"

# Users report
ALERT_SUBJECT_USERS="Alert: Inactive mailbox"

# Admin report
ALERT_SUBJECT_ADMIN="[${HOSTNAME}] Report: Inactive mailboxes"
ALERT_EMAIL_ADMIN="admin@webhostingcompany.com"

# Alias exists (some users need only the alias but create the account unnecessarily)
ALERT_ALIAS_EXISTS="<b>This account has a redirect, you can just keep it and delete the account.</b>"


############################################# 
# send_alert_users FUNCTION
#
function send_alert_users {
	/usr/sbin/sendmail -f ${ALERT_EMAIL_FROM} -t<<EOM
From: ${ALERT_EMAIL_FROM_NAME} <${ALERT_EMAIL_FROM}>
To: ${DAUSEREMAIL}
Subject: ${ALERT_SUBJECT_USERS}
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8

<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
<body style="font-family:Verdana, Arial, Helvetica, sans-serif; font-size:11px;">
	<p>Dear Customer,</p>
	<p>The following e-mail account is not being accessed:</p>
	<blockquote>
	 <b>E-mail</b>: ${USER}@${domain}<br>
	 <b>Unreaded messages</b>: ${NUMFILES_NEW}<br>
	 <b>Oldest message</b>: ${OLDESTFILE_NEW_DDIFF} days ago<br>
	 <b>Disk usage</b>: ${USAGEPERCENT}%<br>
	</blockquote>
	<p>We request the prompt verification or exclusion of the account, if it is no <br>
	longer needed. Inactive accounts for a long period are automatically deleted!</p>
	<p>${ALIAS_MSG}</p>
	<p style="border-left:4px solid #ccc; padding:4px; color:#324f77;">
	You are receiving this automatic alert because the email <b>${DAUSEREMAIL}</b> <br>
	is registered as an administrative contact from user "${username}", responsible for <br>
	domain <b>${domain}</b>. Please let us know if the administrative contact is another.</p>
	<p>Contact us if you have any questions.</p>
	<p>--<br>
	<strong>Webhosting Company Name</strong><br>
	-&gt; http://webhostingcompany.com</p>
</body>
</html>
EOM
}


############################################# 
# send_alert_admin FUNCTION
#
function send_alert_admin {
	/usr/sbin/sendmail -f ${ALERT_EMAIL_FROM} -t<<EOM
From: ${ALERT_EMAIL_FROM_NAME} <${ALERT_EMAIL_FROM}>
To: ${ALERT_EMAIL_ADMIN}
Subject: ${ALERT_SUBJECT_ADMIN}
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8

<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
<body style="font-family:Verdana, Arial, Helvetica, sans-serif; font-size:11px;">
	<p>Dear Admin,</p>
	<p>Below is the report of <b>inactive POP accounts</b> (over ${ALERT_THRESHOLD} days):</p>
	<pre>$1</pre>
	<p>Report generated by $0</p>
</body>
</html>
EOM
}


############################################# 
#

function show_help {
	echo "";
	echo "Usage: $0 [OPTION]";
	echo "";
	echo "List of OPTIONS:";
	echo -e "--display \t\t Just print the report";
	echo -e "--display-debug \t\t Print the report with debug information";
	echo -e "--email \t\t Just e-mail the report";
	echo "";
	exit 0;
}
case "$@" in ""|--help|help|\?|-\?|h) show_help ;; esac

CURRENT_DATE=$(date +%s)

for username in `ls /usr/local/directadmin/data/users 2>/dev/null`; do
{
	HOMEPATH=$(grep -e "^${username}:" /etc/passwd | cut -d: -f6)

	for domain in `cat /usr/local/directadmin/data/users/$username/domains.list 2>/dev/null`; do
	{
		for userquota in `cat /etc/virtual/$domain/quota 2>/dev/null`; do
		{

			((TOTAL_ANALYZED++))

			USER=$(nice echo ${userquota} 2>/dev/null | cut -d: -f1 2>/dev/null)
			MAILDIRPATH="${HOMEPATH}/imap/${domain}/${USER}/Maildir"

			#--display-debug
			case "$@" in --display-debug) echo -e "${TOTAL_ANALYZED} - Probing: ${username} \t ${USER}@${domain}";; esac

			OLDESTFILE_NEW=$(nice find ${MAILDIRPATH}/new -type f -printf '%T@\n' 2>/dev/null |sort |head -n 1 |cut -d. -f1)

			if [ -z $OLDESTFILE_NEW ]; then 
				NEW_MSG="No unseen mails in Maildir/new";
			else
				NUMFILES_NEW=$(nice find ${MAILDIRPATH}/new -type f | wc -l)
				OLDESTFILE_NEW_DDIFF=$(((${CURRENT_DATE} - ${OLDESTFILE_NEW}) / 86400))

				NEW_MSG="${OLDESTFILE_NEW_DDIFF} days (${NUMFILES_NEW} unseen)"

				if nice grep -q "^${USER}:" /etc/virtual/$domain/aliases ; then
					ALIAS_EXISTS=$(nice grep "^${USER}:" /etc/virtual/$domain/aliases |cut -d':' -f2)
					if [ "$(echo ${#ALIAS_EXISTS})" -gt "38" ]; then ALIAS_EXISTS=$(echo ${ALIAS_EXISTS} |cut -c 1-35)."..."; fi
					ALIAS_MSG="$ALERT_ALIAS_EXISTS";
				else
					ALIAS_EXISTS="-";
					ALIAS_MSG="";	
				fi

				if [ $OLDESTFILE_NEW_DDIFF -gt $ALERT_THRESHOLD ]; then

					DAUSEREMAIL=$(awk -F"=" '/email=/ {print $2}' /usr/local/directadmin/data/users/${username}/user.conf)
					QUOTABYTES=$(nice echo ${userquota} 2>/dev/null | cut -d: -f2 2>/dev/null)
					USAGEBYTES=$(nice du -s0 --bytes ${MAILDIRPATH} 2>/dev/null |awk '{print $1}' 2>/dev/null)
					USAGEMB=$(nice echo ${USAGEBYTES}/1048576 |bc)

					if [ "${QUOTABYTES}" -gt "0" ]; then
						QUOTAMB=$(nice echo ${QUOTABYTES}/1048576 |bc)
						USAGEPERCENT=$(nice echo "scale=2; ${USAGEMB}/${QUOTAMB}*100" |/usr/bin/bc |/bin/awk '{printf "%.0f\n", $1}')
						USAGE_MSG="${USAGEMB}MB\t(${USAGEPERCENT}% of ${QUOTAMB}MB)"
					else
						QUOTAMB=0
						USAGEPERCENT=0
						USAGE_MSG="${USAGEMB}MB\t(Unlimited!)"
					fi

					list=$(echo -e "${list}\n${NEW_MSG}\t|\t${USER}@${domain}\t|\t${ALIAS_EXISTS}\t|\t${USAGE_MSG}\t|\t${username}\t|\t${DAUSEREMAIL}")
					USAGEMB_TOTAL=$(($USAGEMB_TOTAL + $USAGEMB))

					case "$@" in --email) send_alert_users ;; esac

					((TOTAL_INACTIVE++))
	
				fi

			fi

		}
		done;
	}
	done;
}
done;

list=$(echo "${list}" | sort -gr -k1,1)
report=$(
 echo -e "
 OLDEST UNSEEN MAIL [1]\t|\tPOP ACCOUNT\t|\tPOP FORWARDING EMAILS TO [2]\t|\tDISK USAGE [3]\t \t|\tDA USER\t|\tNOTIFICATION EMAIL [4]\n
 -----                 \t|\t-----      \t|\t-----                       \t|\t-----         \t \t|\t-----  \t|\t-----
 \n${list}
 -----" | column -t -s $'\t'; 
 echo -e "
 \nCOLUMN DETAILS: 
 [1] OLDEST UNSEEN MAIL: Based on messages stored at user Maildir/new folder, that means it was not retrieved/accessed by any Mail User Agent (Outlook, Webmail, etc).
 [2] POP FORWARDING EMAILS TO: If the account is inactive and messages are forwarded to another account, probably only the redirection is necessary.
 [3] DISK USAGE: Total POP account size, including IMAP folders, read and unread messages.
 [4] NOTIFICATION EMAIL: Obtained from DirectAdmin user details page. The alert is sent to this email if the script is run with the option --email.
 \nSTATS: 
 -> Inactive accounts: ${TOTAL_INACTIVE} of ${TOTAL_ANALYZED} analyzed 
 -> Total wasted space: ${USAGEMB_TOTAL}MB
 -> Script running time: ${SECONDS}s"
)

case "$@" in --email) if [ -n "$list" ]; then send_alert_admin "${report}"; fi ;; esac
case "$@" in --display|--display-debug) echo -e "${report}" ;; esac
