#!/bin/bash

#########################################################################
#
# E-mail quota alert and usage report to be used with DirecAdmin control 
# panel with Dovecot Maildir.
#
# More useful if used as cronjob, especially at server low load periods.
# Example to run every 3 days at 6:30 a.m.:
#
# Create a cronjob file (/etc/cron.d/alert-pop-usage.cron) with the line:
# 30 6 */3 * * root /path/alert-pop-usage.sh --email
# Remember to change the /path, chmod this script to 700 and chown to root
#
# Author: Victor Benincasa (vbenincasa @ gmail.com) 
# Originally developed for Unihost Brasil (http://unihostbrasil.com.br)
#
# Free to use and redistribute, just keep the original credits.
#
# V 2.5 09/03/2015 14:08:38
#
#########################################################################

############################################# 
# CONFIGURATION
#

# Usage alert threshold. From 0.10 (10%) to 1 (100%). Suggested value: 0.90 (90%)
ALERT_THRESHOLD=0.90

# Also report POP accounts with unlimited quota (set to 0 at Directadmin). Value: true or false.
REPORT_UNLIMITED=true

# From address used to send e-mail to users and admin
ALERT_EMAIL_FROM_NAME="Webhosting Company Name"
ALERT_EMAIL_FROM="sendermail@domain.com"

# Users report
ALERT_SUBJECT_USERS="Alert: E-mail account close to capacity"

# Admin report
ALERT_SUBJECT_ADMIN="[${HOSTNAME}] Report: E-mail accounts close to capacity"
ALERT_EMAIL_ADMIN="admin@webhostingcompany.com"


############################################# 
# send_alert_users FUNCTION
#
function send_alert_users {
	/usr/sbin/sendmail -f ${ALERT_EMAIL_FROM} -t<<EOM
From: ${ALERT_EMAIL_FROM_NAME} <${ALERT_EMAIL_FROM}>
To: ${DAUSEREMAIL}
Subject: ${ALERT_SUBJECT_USERS}
MIME-Version: 1.0
Content-Type: text/html; charset=iso-8859-1

<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"></head>
<body style="font-family:Verdana, Arial, Helvetica, sans-serif; font-size:11px;">
	<p>Dear Customer,</p>
	<p>The following e-mail account is near or has reached its storage limit, poiting <br>
	that it's not being verified or contain too many messages stored.</p>
	<blockquote>
	 <b>E-mail</b>: ${USER}@${domain}<br>
	 <b>Disk Usage</b>: ${USAGEPERCENT}%<br>
	</blockquote>
	<p>Full mailboxes can not receive new messages and occupy resources of your hosting account.</p>
	<p>Please free some space, increase the account storage limit or delete it if it's no longer needed.</p>
	<p style="border-left:4px solid #ccc; padding:4px; color:#324f77;">
	You are receiving this automatic alert because the email <b>${DAUSEREMAIL}</b> <br>
	is registered as an administrative contact from user "${username}", responsible for <br>
	domain <b>${domain}</b>. Please let us know if the administrative contact is another.</p>
	<p>Contact us if you have any questions.</p>
	<p>--<br>
	<strong>Webhosting Company Name</strong><br>
  -&gt; http://webhostingcompany.com</p>
</body>
</html>
EOM
}


############################################# 
# send_alert_admin FUNCTION
#
function send_alert_admin {
	/usr/sbin/sendmail -f ${ALERT_EMAIL_FROM} -t<<EOM
From: ${ALERT_EMAIL_FROM_NAME} <${ALERT_EMAIL_FROM}>
To: ${ALERT_EMAIL_ADMIN}
Subject: ${ALERT_SUBJECT_ADMIN}
MIME-Version: 1.0
Content-Type: text/html; charset=iso-8859-1

<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"></head>
<body style="font-family:Verdana, Arial, Helvetica, sans-serif; font-size:11px;">
	<p>Dear Admin,</p>
	<p>Below is the report of <b>overquota POP accounts</b> (usage over ${ALERT_THRESHOLD}):</p>
	<pre>$1</pre>
	<p>Report generated by $0</p>
</body>
</html>
EOM
}


############################################# 
# Main processing
#

function show_help {
	echo "";
	echo "Usage: $0 [OPTION]";
	echo "";
	echo "List of OPTIONS:";
	echo -e "--display \t\t Just print the report";
	echo -e "--display-debug \t\t Print the report with debug information";
	echo -e "--email \t\t Just e-mail the report";
	echo "";
	exit 0;
}
case "$@" in ""|--help|help|\?|-\?|h) show_help ;; esac

CURRENT_DATE=$(date +%s)

for username in `ls /usr/local/directadmin/data/users 2>/dev/null`; do
{
	for domain in `cat /usr/local/directadmin/data/users/$username/domains.list 2>/dev/null`; do
	{
		for userquota in `cat /etc/virtual/$domain/quota 2>/dev/null`; do
		{

			((TOTAL_ANALYZED++))

			USER=$(nice echo ${userquota} 2>/dev/null | cut -d: -f1 2>/dev/null)
			MAILDIRPATH="/home/${username}/imap/${domain}/${USER}"

			QUOTABYTES=$(nice echo ${userquota} 2>/dev/null | cut -d: -f2 2>/dev/null)
			USAGEKB=$(nice du -s0 ${MAILDIRPATH} 2>/dev/null |awk '{print $1}' 2>/dev/null)

			#--display-debug
			case "$@" in --display-debug) echo -e "${TOTAL_ANALYZED} - Probing: ${username} \t ${USER}@${domain} Usage:(${USAGEKB}KB/${QUOTABYTES}B)";; esac

			if [ "${QUOTABYTES}" -gt "0" ]; then
				#Quota is set

				QUOTAKB=$(nice echo ${QUOTABYTES}/1024 |bc)
				LIMIT=$(nice echo ${QUOTAKB}*${ALERT_THRESHOLD} |bc |awk '{printf "%.0f\n", $1}')

				if [ $USAGEKB -gt $LIMIT ]; then

					USAGEMB=$(echo ${USAGEKB}/1024 |bc)
					QUOTAMB=$(echo ${QUOTAKB}/1024 |bc)
					DAUSEREMAIL=$(awk -F"=" '/email=/ {print $2}' /usr/local/directadmin/data/users/${username}/user.conf)
					USAGEPERCENT=$(nice echo "scale=2; ${USAGEMB}/${QUOTAMB}*100" |/usr/bin/bc |/bin/awk '{printf "%.0f\n", $1}')
	
					if nice grep -q "${USER}:" /etc/virtual/$domain/aliases ; then
						ALIAS_EXISTS=$(nice grep "${USER}:" /etc/virtual/$domain/aliases |cut -d':' -f2)
						if [ "$(echo ${#ALIAS_EXISTS})" -gt "38" ]; then ALIAS_EXISTS=$(echo ${ALIAS_EXISTS} |cut -c 1-35)."..."; fi
						ALIAS_MSG="$ALERT_ALIAS_EXISTS";
					else
						ALIAS_EXISTS="-";
						ALIAS_MSG="";	
					fi
	
					OLDESTFILE_NEW=$(nice find ${MAILDIRPATH}/Maildir/new -type f -printf '%T@\n' 2>/dev/null |sort |head -n 1 |cut -d. -f1)
					OLDESTFILE_CUR=$(nice find ${MAILDIRPATH}/Maildir/cur -type f -printf '%T@\n' 2>/dev/null |sort |head -n 1 |cut -d. -f1)
	
					if [ -z $OLDESTFILE_NEW ]; then 
						NEW_MSG="No unretrieved mail";
					else
						NUMFILES_NEW=$(nice find ${MAILDIRPATH}/Maildir/new -type f | wc -l)
						OLDESTFILE_NEW_DDIFF=$(((${CURRENT_DATE} - ${OLDESTFILE_NEW}) / 86400))
						NEW_MSG="${OLDESTFILE_NEW_DDIFF} days (${NUMFILES_NEW} unretrieved)"
					fi
	
					if [ -z $OLDESTFILE_CUR ]; then 
						CUR_MSG="No stored mails in Maildir/cur";
					else
						NUMFILES_CUR=$(nice find ${MAILDIRPATH}/Maildir/cur -type f | wc -l)
						OLDESTFILE_CUR_DDIFF=$(((${CURRENT_DATE} - ${OLDESTFILE_CUR}) / 86400))
						CUR_MSG="${OLDESTFILE_CUR_DDIFF} days (${NUMFILES_CUR} stored)"
					fi
	
					list=$(echo -e "${list}\n${USAGEPERCENT}%\t(${USAGEMB}/${QUOTAMB}MB)\t|\t${USER}@${domain}\t|\t${NEW_MSG}\t|\t${CUR_MSG}\t|\t${ALIAS_EXISTS}\t|\t${username}\t|\t${DAUSEREMAIL}")
	
					case "$@" in --email) send_alert_users ;; esac
	
					((TOTAL_OVERQUOTA++))
	
				fi

			elif ${REPORT_UNLIMITED}; then
				#Unlimited quota

				USAGEMB=$(echo ${USAGEKB}/1024 |bc)
				list=$(echo -e "${list}\n0%\t(${USAGEMB}MB/Unlimited)\t|\t${USER}@${domain}\t|\t-\t|\t-\t|\t-\t|\t${username}\t|\t-")
			fi

		}
		done;
	}
	done;
}
done;

list=$(echo "${list}" | sort -gr -k1,1)
report=$(
echo -e "
 QUOTA USAGE\t \t|\tPOP ACCOUNT\t|\tOLDEST UNRETRIEVED MAIL [1]\t|\tOLDEST STORED MAIL IN INBOX [2]\t|\tPOP FORWARDING EMAILS TO [3]\t|\tDA USER\t|\tNOTIFICATION EMAIL [4]\n
 -----      \t \t|\t-----      \t|\t-----                      \t|\t-----                          \t|\t-----                       \t|\t-----  \t|\t-----
 \n${list}
 -----" | column -t -s $'\t'; 
 echo -e "
 \nCOLUMN DETAILS: 
 [1] OLDEST UNRETRIEVED MAIL: Usefull to estimate the account inactivity. Based on messages stored at user Maildir/new folder, that means it was not retrieved/accessed by any Mail User Agent (Outlook, Webmail, etc).
 [2] OLDEST STORED MAIL IN INBOX: Helps to determine if the account is used for long-term message storage.
 [3] POP FORWARDING EMAILS TO: If the account is inactive and messages are forwarded to another account, probably only the redirection is necessary.
 [4] NOTIFICATION EMAIL: Obtained from DirectAdmin user details page. The alert is sent to this email if the script is run with the option --email.
 \nSTATS: 
 -> Overquota accounts: ${TOTAL_OVERQUOTA} of ${TOTAL_ANALYZED} analyzed
 -> Script running time: ${SECONDS}s"
)

case "$@" in --email) if [ -n "$list" ]; then send_alert_admin "${report}"; fi ;; esac
case "$@" in --display|--display-debug) echo -e "${report}" ;; esac
